services:
  - type: static_site
    name: psych-dev-site
    env: static
    buildCommand: npm i --legacy-peer-deps && npm run build
    staticPublishPath: dist
    routes:
      # - type: redirect
      #   source: /
      #   destination: /prenatal
      #   statusCode: 302
      - type: rewrite
        source: /*
        destination: /index.html
