import type { RouteConfig } from './types';

export const GENERAL_ROUTE_CONFIG: RouteConfig[] = [
  {
    path: '/general/intro',
    key: 'general-intro',
    navLabel: 'Введение',
    periodId: 'general-intro',
    themeKey: 'general',
    placeholderText:
      'На этой вводной странице собрана общая информация о курсе общей психологии, формате занятий и итоговой аттестации. Ниже переходите к первой теме.',
    placeholderDefaultEnabled: true,
    meta: {
      title: 'Введение в курс общей психологии — DOM Academy',
      description: 'Общая информация о курсе, структуре занятий и экзамене.',
    },
  },
  {
    path: '/general/1',
    key: 'general-1',
    navLabel: 'История психологии и методы',
    periodId: 'general-1',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'История психологии и методы — DOM Academy',
      description: 'История психологии, подходы и методы исследования.',
    },
  },
  {
    path: '/general/2',
    key: 'general-2',
    navLabel: 'Методологические проблемы',
    periodId: 'general-2',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Методологические проблемы — DOM Academy',
      description: 'Методологические проблемы изучения психики.',
    },
  },
  {
    path: '/general/3',
    key: 'general-3',
    navLabel: 'Ощущение и восприятие',
    periodId: 'general-3',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Ощущение и восприятие — DOM Academy',
      description: 'Свойства образов и теории восприятия.',
    },
  },
  {
    path: '/general/4',
    key: 'general-4',
    navLabel: 'Внимание',
    periodId: 'general-4',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Внимание — DOM Academy',
      description: 'Классические и когнитивные модели внимания.',
    },
  },
  {
    path: '/general/5',
    key: 'general-5',
    navLabel: 'Память. Часть 1',
    periodId: 'general-5',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Память. Часть 1 — DOM Academy',
      description: 'Классика, конструкции и искажения памяти.',
    },
  },
  {
    path: '/general/6',
    key: 'general-6',
    navLabel: 'Память. Часть 2',
    periodId: 'general-6',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Память. Часть 2 — DOM Academy',
      description: 'Когнитивные модели и функции памяти.',
    },
  },
  {
    path: '/general/7',
    key: 'general-7',
    navLabel: 'Мышление',
    periodId: 'general-7',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Мышление — DOM Academy',
      description: 'Развитие мышления, интериоризация и когнитивные искажения.',
    },
  },
  {
    path: '/general/8',
    key: 'general-8',
    navLabel: 'Речь',
    periodId: 'general-8',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Речь — DOM Academy',
      description: 'Взаимосвязь речи и мышления, язык и билингвизм.',
    },
  },
  {
    path: '/general/9',
    key: 'general-9',
    navLabel: 'Эмоциональная сфера',
    periodId: 'general-9',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Эмоциональная сфера — DOM Academy',
      description: 'Теории эмоций, классификация и эволюция.',
    },
  },
  {
    path: '/general/10',
    key: 'general-10',
    navLabel: 'Чувства и регуляция',
    periodId: 'general-10',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Чувства и регуляция — DOM Academy',
      description: 'Регуляция эмоций и кросс-культурные исследования.',
    },
  },
  {
    path: '/general/11',
    key: 'general-11',
    navLabel: 'Мотивация',
    periodId: 'general-11',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Мотивация — DOM Academy',
      description: 'Теории мотивации и место в структуре личности.',
    },
  },
  {
    path: '/general/12',
    key: 'general-12',
    navLabel: 'Саморегуляция и воля',
    periodId: 'general-12',
    themeKey: 'general',
    placeholderDefaultEnabled: false,
    meta: {
      title: 'Саморегуляция и воля — DOM Academy',
      description: 'Функции воли, онтогенез и практические модели.',
    },
  },
];
