import { buildTranscriptFullText, buildTranscriptPreview, buildVideoTranscriptStoragePath, getTranscriptDurationMs } from "./helpers.js";
import {
  VIDEO_TRANSCRIPT_VERSION,
  type VideoTranscriptDocShape,
  type VideoTranscriptStoragePayload,
} from "./schema.js";
import type {
  ImportStatus,
  TranscriptImportResult,
  TranscriptImportTarget,
} from "./importTypes.js";
import {
  buildAvailableRetryFields,
  buildEmptyTranscriptDoc,
  buildFailedRetryFields,
} from "./retry.js";

export function buildTranscriptPendingDoc<TTimestamp>(youtubeVideoId: string, now: TTimestamp) {
  return {
    ...buildEmptyTranscriptDoc(youtubeVideoId, now),
    status: "pending" as const,
  };
}

export function buildTranscriptAvailablePayload<TTimestamp>(
  target: TranscriptImportTarget,
  transcript: TranscriptImportResult,
  now: TTimestamp
) {
  const fullText = buildTranscriptFullText(transcript.segments);
  const durationMs = getTranscriptDurationMs(transcript.segments);
  const storagePath = buildVideoTranscriptStoragePath(
    target.youtubeVideoId,
    VIDEO_TRANSCRIPT_VERSION
  );

  const storagePayload: VideoTranscriptStoragePayload = {
    youtubeVideoId: target.youtubeVideoId,
    version: VIDEO_TRANSCRIPT_VERSION,
    source: "youtube",
    language: transcript.language,
    languageName: null,
    isAutoGenerated: null,
    fetchedAt: new Date().toISOString(),
    durationMs,
    fullText,
    segments: transcript.segments,
  };

  const docPayload: VideoTranscriptDocShape<TTimestamp> = {
    ...buildEmptyTranscriptDoc(target.youtubeVideoId, now),
    ...buildAvailableRetryFields<TTimestamp>(),
    availableLanguages: transcript.availableLanguages,
    durationMs,
    fetchedAt: now,
    fullTextPreview: buildTranscriptPreview(fullText),
    language: transcript.language,
    lastCheckedAt: now,
    segmentCount: transcript.segments.length,
    status: "available",
    storagePath,
    textLength: fullText.length,
    updatedAt: now,
  };

  return {
    docPayload,
    storagePath,
    storagePayload,
  };
}

export function buildTranscriptFailedDoc<TTimestamp>(
  youtubeVideoId: string,
  status: ImportStatus,
  errorCode: string,
  errorMessage: string,
  availableLanguages: string[],
  retryCount: number,
  now: TTimestamp,
  nextRetryAt: TTimestamp
) {
  const docPayload: VideoTranscriptDocShape<TTimestamp> = {
    ...buildEmptyTranscriptDoc(youtubeVideoId, now),
    ...buildFailedRetryFields(retryCount, now, nextRetryAt, errorCode),
    availableLanguages,
    errorCode,
    errorMessage,
    lastCheckedAt: now,
    status,
    updatedAt: now,
  };

  return docPayload;
}
