import {
  VIDEO_TRANSCRIPT_VERSION,
  type VideoTranscriptDocShape,
  type VideoTranscriptRetryFields,
} from "./schema.js";

const RETRY_DELAYS_IN_DAYS = [7, 14, 30];

export function getTranscriptRetryDelayDays(retryCount: number) {
  const normalizedRetryCount = Math.max(1, retryCount);
  return RETRY_DELAYS_IN_DAYS[Math.min(normalizedRetryCount - 1, RETRY_DELAYS_IN_DAYS.length - 1)];
}

export function addDays(date: Date, days: number) {
  return new Date(date.getTime() + days * 24 * 60 * 60 * 1000);
}

export function buildNextRetryDate(now: Date, retryCount: number) {
  return addDays(now, getTranscriptRetryDelayDays(retryCount));
}

export function buildFailedRetryFields<TTimestamp>(
  retryCount: number,
  now: TTimestamp,
  nextRetryAt: TTimestamp,
  lastRetryReason: string
): VideoTranscriptRetryFields<TTimestamp> {
  return {
    retryCount,
    lastRetryAt: now,
    nextRetryAt,
    lastRetryReason,
  };
}

export function buildAvailableRetryFields<TTimestamp>(): VideoTranscriptRetryFields<TTimestamp> {
  return {
    retryCount: 0,
    lastRetryAt: null,
    nextRetryAt: null,
    lastRetryReason: null,
  };
}

export function getExistingRetryCount<TTimestamp>(
  doc: Partial<VideoTranscriptDocShape<TTimestamp>> | undefined
) {
  return typeof doc?.retryCount === "number" && Number.isFinite(doc.retryCount)
    ? doc.retryCount
    : 0;
}

export function buildEmptyTranscriptDoc<TTimestamp>(
  youtubeVideoId: string,
  now: TTimestamp
): Omit<VideoTranscriptDocShape<TTimestamp>, "updatedAt" | "lastCheckedAt" | "fetchedAt"> & {
  updatedAt: TTimestamp;
  lastCheckedAt: TTimestamp;
  fetchedAt: TTimestamp | null;
} {
  return {
    youtubeVideoId,
    source: "youtube",
    status: "pending",
    language: null,
    languageName: null,
    isAutoGenerated: null,
    availableLanguages: [],
    storagePath: null,
    version: VIDEO_TRANSCRIPT_VERSION,
    segmentCount: 0,
    durationMs: null,
    textLength: 0,
    fullTextPreview: null,
    fetchedAt: null,
    updatedAt: now,
    lastCheckedAt: now,
    errorCode: null,
    errorMessage: null,
    retryCount: 0,
    lastRetryAt: null,
    nextRetryAt: null,
    lastRetryReason: null,
  };
}
