export const VIDEO_TRANSCRIPTS_COLLECTION = "videoTranscripts";
export const VIDEO_TRANSCRIPT_STORAGE_PREFIX = "video-transcripts";
export const VIDEO_TRANSCRIPT_VERSION = 1;
export const VIDEO_TRANSCRIPT_JOBS_COLLECTION = "transcriptJobs";
export const WEEKLY_TRANSCRIPT_REFRESH_JOB = "weeklyRefresh";
export const VIDEO_TRANSCRIPT_JOB_RUNS_SUBCOLLECTION = "runs";

export type VideoTranscriptStatus =
  | "pending"
  | "available"
  | "unavailable"
  | "failed";

export interface VideoTranscriptSegment {
  index: number;
  startMs: number;
  endMs: number;
  durationMs: number;
  text: string;
}

export interface VideoTranscriptStoragePayload {
  youtubeVideoId: string;
  version: number;
  source: "youtube";
  language: string | null;
  languageName: string | null;
  isAutoGenerated: boolean | null;
  fetchedAt: string;
  durationMs: number | null;
  fullText: string;
  segments: VideoTranscriptSegment[];
}

export interface VideoTranscriptRetryFields<TTimestamp> {
  retryCount: number;
  lastRetryAt: TTimestamp | null;
  nextRetryAt: TTimestamp | null;
  lastRetryReason: string | null;
}

export interface VideoTranscriptDocShape<TTimestamp>
  extends VideoTranscriptRetryFields<TTimestamp> {
  youtubeVideoId: string;
  source: "youtube";
  status: VideoTranscriptStatus;
  language: string | null;
  languageName: string | null;
  isAutoGenerated: boolean | null;
  availableLanguages?: string[];
  storagePath: string | null;
  version: number;
  segmentCount: number;
  durationMs: number | null;
  textLength: number;
  fullTextPreview: string | null;
  fetchedAt: TTimestamp | null;
  updatedAt: TTimestamp;
  lastCheckedAt: TTimestamp;
  errorCode: string | null;
  errorMessage: string | null;
}

export type TranscriptRefreshJobStatus =
  | "idle"
  | "running"
  | "completed"
  | "failed";

export interface TranscriptRefreshJobDocShape<TTimestamp> {
  jobName: string;
  status: TranscriptRefreshJobStatus;
  startedAt: TTimestamp | null;
  finishedAt: TTimestamp | null;
  expiresAt: TTimestamp | null;
  updatedAt: TTimestamp;
  lastRunId: string | null;
  lastTrigger: "scheduled" | "manual" | null;
  lastError: string | null;
}

export interface TranscriptRefreshJobRunDocShape<TTimestamp> {
  jobName: string;
  trigger: "scheduled" | "manual";
  status: "running" | "completed" | "failed" | "skipped";
  startedAt: TTimestamp;
  finishedAt: TTimestamp | null;
  updatedAt: TTimestamp;
  processedCount: number;
  availableCount: number;
  unavailableCount: number;
  failedCount: number;
  skippedCount: number;
  scannedVideoCount: number;
  candidateCount: number;
  errorSummary: string[];
}
