import type { Timestamp } from 'firebase/firestore';

export const VIDEO_TRANSCRIPTS_COLLECTION = 'videoTranscripts';
export const VIDEO_TRANSCRIPT_STORAGE_PREFIX = 'video-transcripts';
export const VIDEO_TRANSCRIPT_VERSION = 1;

export type VideoTranscriptStatus =
  | 'pending'
  | 'available'
  | 'unavailable'
  | 'failed';

export interface VideoTranscriptSegment {
  index: number;
  startMs: number;
  endMs: number;
  durationMs: number;
  text: string;
}

export interface VideoTranscriptStoragePayload {
  youtubeVideoId: string;
  version: number;
  source: 'youtube';
  language: string | null;
  languageName: string | null;
  isAutoGenerated: boolean | null;
  fetchedAt: string;
  durationMs: number | null;
  fullText: string;
  segments: VideoTranscriptSegment[];
}

export interface VideoTranscriptDoc {
  youtubeVideoId: string;
  source: 'youtube';
  status: VideoTranscriptStatus;
  language: string | null;
  languageName: string | null;
  isAutoGenerated: boolean | null;
  availableLanguages?: string[];
  storagePath: string | null;
  version: number;
  segmentCount: number;
  durationMs: number | null;
  textLength: number;
  fullTextPreview: string | null;
  fetchedAt: Timestamp | null;
  updatedAt: Timestamp;
  lastCheckedAt: Timestamp;
  errorCode: string | null;
  errorMessage: string | null;
}
