export type BiographyExtractorBenchmarkMatcher = {
  any?: string[];
  all?: string[][];
};

export type BiographyExtractorBenchmarkFact = {
  id: string;
  year?: number;
  label: string;
  critical?: boolean;
  themes?: string[];
  article?: BiographyExtractorBenchmarkMatcher;
  extractor?: BiographyExtractorBenchmarkMatcher;
};

export type BiographyExtractorBenchmark = {
  id: string;
  subject: string;
  sourceUrl: string;
  facts: BiographyExtractorBenchmarkFact[];
};

const gandhiFacts: BiographyExtractorBenchmarkFact[] = [
  {
    id: 'birth-porbandar',
    year: 1869,
    label: 'Рождение в Порбандаре',
    critical: true,
    themes: ['family_household'],
    article: { all: [['2 октября 1869', 'порбандар']] },
    extractor: { any: ['рождение в порбандаре', 'родился в порбандаре', 'порбандар'] },
  },
  {
    id: 'bania-vaishya-family',
    label: 'Происходил из семьи касты банья варны вайшьев',
    themes: ['family_household'],
    article: { all: [['касте банья', 'варне вайшьев']] },
    extractor: { any: ['банья', 'вайшь', 'торгово ростовщической касте'] },
  },
  {
    id: 'father-divan',
    label: 'Отец Карамчанд Ганди был диваном Порбандара',
    themes: ['family_household', 'service_career'],
    article: { all: [['карамчанд ганди', 'дивана', 'порбандара']] },
    extractor: { any: ['карамчанд', 'диван порбандара', 'главного министра порбандара'] },
  },
  {
    id: 'mother-piety',
    label: 'Набожная мать и религиозно-вегетарианское воспитание',
    themes: ['upbringing_mentors'],
    article: { all: [['особенно набожной была его мать', 'строжайшее вегетарианство']] },
    extractor: { any: ['мать путлибай', 'набожной была его мать', 'строжайшее вегетарианство'] },
  },
  {
    id: 'marriage-kasturba',
    year: 1882,
    label: 'Женился на Кастурбе в 13 лет',
    critical: true,
    themes: ['family_household', 'romance'],
    article: { all: [['13 лет', 'кастурб']] },
    extractor: { any: ['кастурб', 'женили ганди', 'брак с кастурб'] },
  },
  {
    id: 'four-sons',
    label: 'У Ганди и Кастурбы родилось четверо сыновей',
    themes: ['children', 'family_household'],
    article: { all: [['четверо сыновей', 'супругов ганди']] },
    extractor: { any: ['четверо сыновей', 'четыре сына', 'сыновей'] },
  },
  {
    id: 'harilal-estrangement',
    label: 'Отказался от старшего сына Харилала',
    themes: ['family_household', 'conflict_duels'],
    article: { all: [['харилала', 'отец отказался']] },
    extractor: { any: ['харилал', 'отказался от старшего сына', 'отец отказался'] },
  },
  {
    id: 'london-departure',
    year: 1888,
    label: 'В 19 лет отправился в Лондон',
    critical: true,
    themes: ['education', 'travel_moves_exile'],
    article: { all: [['в 19 лет', 'отправился в лондон']] },
    extractor: { any: ['отправился в лондон', 'поездка в лондон', 'лондон'] },
  },
  {
    id: 'legal-education',
    year: 1888,
    label: 'Получил юридическое образование в Лондоне',
    critical: true,
    themes: ['education'],
    article: { all: [['получил юридическое образование', 'лондон']] },
    extractor: { any: ['юридическое образование', 'изучал право', 'закончил юридическое образование'] },
  },
  {
    id: 'return-india-1891',
    year: 1891,
    label: 'Вернулся в Индию после учёбы',
    themes: ['travel_moves_exile'],
    article: { all: [['1891', 'вернулся в индию']] },
    extractor: { any: ['вернулся в индию', '1891'] },
  },
  {
    id: 'failed-career-india',
    year: 1891,
    label: 'Юридическая практика в Индии не принесла успеха',
    themes: ['service_career'],
    article: { all: [['профессиональная деятельность на родине', 'не принесла', 'успеха']] },
    extractor: { any: ['не принесла ганди особого успеха', 'неудача в профессиональной деятельности', 'не принесла успеха'] },
  },
  {
    id: 'south-africa-1893',
    year: 1893,
    label: 'Отправился работать в Южную Африку',
    critical: true,
    themes: ['travel_moves_exile', 'service_career'],
    article: { all: [['1893', 'южную африку']] },
    extractor: { any: ['южную африку', 'переезд в южную африку', 'отправился работать в южную африку'] },
  },
  {
    id: 'rights-of-indians-south-africa',
    label: 'Начал борьбу за права индийцев в Южной Африке',
    critical: true,
    themes: ['service_career', 'politics_public_pressure'],
    article: { all: [['борьбу за права индийцев', 'южной африке']] },
    extractor: { any: ['борьбу за права индийцев', 'права индийцев в южной африке'] },
  },
  {
    id: 'first-satyagraha',
    label: 'Впервые применил сатьяграху',
    critical: true,
    themes: ['politics_public_pressure', 'service_career'],
    article: { all: [['впервые применил', 'сатьяграха']] },
    extractor: { any: ['впервые применил', 'сатьяграха', 'ненасильственное сопротивление'] },
  },
  {
    id: 'bhagavad-gita-influence',
    label: 'На мировоззрение повлияла Бхагавадгита',
    themes: ['legacy'],
    article: { all: [['бхагавадгита', 'оказала влияние']] },
    extractor: { any: ['бхагавадгита', 'библия индуизма'] },
  },
  {
    id: 'tolstoy-influence',
    label: 'Испытал влияние Толстого и переписывался с ним',
    themes: ['friends_network', 'legacy'],
    article: { all: [['толстого', 'переписке']] },
    extractor: { any: ['толст', 'переписке', 'переписывался с толстым'] },
  },
  {
    id: 'other-intellectual-influences',
    label: 'Отмечал влияние Торо, Шримада Раджчандры, Майкла Девитта и Рёскина',
    themes: ['legacy'],
    article: { all: [['торо', 'рёскина']] },
    extractor: { any: ['торо', 'раджчандр', 'майкла девитта', 'рёскин'] },
  },
  {
    id: 'return-india-1915',
    year: 1915,
    label: 'Возвратился в Индию в 1915 году',
    critical: true,
    themes: ['travel_moves_exile'],
    article: { all: [['1915', 'возвратился в индию']] },
    extractor: { any: ['1915', 'возвратился в индию', 'вернулся в индию'] },
  },
  {
    id: 'tagore-mahatma-title',
    year: 1915,
    label: 'Рабиндранат Тагор впервые назвал его Махатмой',
    themes: ['friends_network', 'legacy'],
    article: { all: [['рабиндранат тагор', 'впервые применил', 'махатма']] },
    extractor: { any: ['тагор', 'махатма', 'великая душа'] },
  },
  {
    id: 'disliked-mahatma-title',
    year: 1915,
    label: 'Сам Ганди говорил, что титул Махатма его огорчает',
    themes: ['legacy'],
    article: { all: [['титул огорчает его', 'махатма']] },
    extractor: { any: ['титул огорчает', 'махатма его огорчает'] },
  },
  {
    id: 'tilak-successor',
    label: 'Тилак объявил Ганди своим преемником',
    themes: ['service_career', 'friends_network'],
    article: { all: [['тилак', 'своим преемником']] },
    extractor: { any: ['тилак', 'преемником'] },
  },
  {
    id: 'active-independence-1919',
    year: 1919,
    label: 'Через четыре года после возвращения активно включился в движение за независимость',
    critical: true,
    themes: ['service_career', 'politics_public_pressure'],
    article: { all: [['через 4 года', 'движение за достижение независимости']] },
    extractor: { any: ['движение за независимость', 'через 4 года', 'активно включился'] },
  },
  {
    id: 'boycott-british-goods',
    label: 'Продвигал бойкот британских товаров и учреждений',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['бойкоту британских товаров и учреждений']] },
    extractor: { any: ['бойкот британских товаров', 'бойкот британских учреждений'] },
  },
  {
    id: 'civil-disobedience',
    label: 'Призывал демонстративно нарушать законы',
    themes: ['politics_public_pressure'],
    article: { all: [['демонстративно нарушали ряд законов']] },
    extractor: { any: ['нарушали ряд законов', 'гражданское неповиновение', 'демонстративно нарушать'] },
  },
  {
    id: 'led-inc-1921',
    year: 1921,
    label: 'Возглавил Индийский национальный конгресс',
    critical: true,
    themes: ['service_career', 'politics_public_pressure'],
    article: { all: [['1921', 'возглавил индийский национальный конгресс']] },
    extractor: { any: ['возглавил индийский национальный конгресс', 'инк'] },
  },
  {
    id: 'salt-march-1930',
    year: 1930,
    label: 'Возглавил Соляной поход против налога на соль',
    critical: true,
    themes: ['politics_public_pressure', 'service_career'],
    article: { all: [['1930', 'соляной поход']] },
    extractor: { any: ['соляной поход', 'налога на соль'] },
  },
  {
    id: 'left-inc-1934',
    year: 1934,
    label: 'Покинул Индийский национальный конгресс',
    themes: ['service_career', 'conflict_duels'],
    article: { all: [['1934', 'покинул', 'индийский национальный конгресс']] },
    extractor: { any: ['покинул индийский национальный конгресс', 'покинул инк'] },
  },
  {
    id: 'fight-untouchability',
    label: 'Вёл непримиримую борьбу с неприкасаемостью',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['непримиримая борьба', 'неприкасаемости']] },
    extractor: { any: ['борьба с неприкасаемостью', 'кастовым неравенством'] },
  },
  {
    id: 'harijans-term',
    label: 'Стал называть неприкасаемых хариджанами',
    themes: ['politics_public_pressure'],
    article: { all: [['стал называть хариджанами']] },
    extractor: { any: ['хариджан', 'детьми божьими'] },
  },
  {
    id: 'ashram-and-meals-with-harijans',
    label: 'Допускал хариджанов в ашрам и разделял с ними трапезу',
    themes: ['politics_public_pressure', 'family_household'],
    article: { all: [['допускал хариджанов в свой ашрам', 'разделял с ними трапезу']] },
    extractor: { any: ['хариджанов в свой ашрам', 'разделял с ними трапезу', 'ашрам'] },
  },
  {
    id: 'fasts-for-harijan-rights',
    label: 'Объявлял голодовки в защиту прав хариджанов',
    critical: true,
    themes: ['politics_public_pressure', 'health'],
    article: { all: [['голодовки', 'в защиту их прав']] },
    extractor: { any: ['голодовк', 'в защиту прав', 'хариджан'] },
  },
  {
    id: 'conflict-with-ambedkar',
    label: 'Вступил в глубокий конфликт с Амбедкаром',
    critical: true,
    themes: ['conflict_duels', 'friends_network', 'politics_public_pressure'],
    article: { all: [['глубокие разногласия', 'амбедкар']] },
    extractor: { any: ['амбедкар', 'разногласия', 'конфликт с амбедкаром'] },
  },
  {
    id: 'fast-1932-ambedkar-compromise',
    year: 1932,
    label: 'Голодовка 1932 года заставила Амбедкара пойти на уступки',
    critical: true,
    themes: ['health', 'conflict_duels', 'politics_public_pressure'],
    article: { all: [['1932', 'голодовка', 'амбедкара', 'уступки']] },
    extractor: { any: ['1932', 'амбедкар', 'голодовк', 'уступ'] },
  },
  {
    id: 'charaka-sangh',
    label: 'Создал организацию Чарка Сангх',
    themes: ['service_career', 'project'],
    article: { all: [['чарка сангх']] },
    extractor: { any: ['чарка сангх', 'charaka sangh'] },
  },
  {
    id: 'harijan-sevak-sangh',
    label: 'Создал Хариджан Севак Сангх',
    themes: ['service_career', 'project'],
    article: { all: [['хариджан севак сангх']] },
    extractor: { any: ['хариджан севак сангх', 'harijan sevak sangh'] },
  },
  {
    id: 'brahmacharya-vow-1906',
    year: 1906,
    label: 'Принял обет брахмачарьи',
    themes: ['health', 'legacy'],
    article: { all: [['1906', 'обет брахмачарьи']] },
    extractor: { any: ['обет брахмачарьи', 'целомудрия', '1906'] },
  },
  {
    id: 'translated-letter-to-a-hindu',
    year: 1909,
    label: 'Перевёл и опубликовал Письмо индусу Толстого',
    themes: ['creative_work', 'legacy'],
    article: { all: [['1909', 'письмо индусу']] },
    extractor: { any: ['письмо индусу', 'толстого', '1909'] },
  },
  {
    id: 'munich-crisis-test',
    year: 1938,
    label: 'Мюнхенский кризис стал испытанием для его принципа ненасилия',
    themes: ['politics_public_pressure'],
    article: { all: [['мюнхенского кризиса', 'принцип ненасилия']] },
    extractor: { any: ['мюнхенск', 'принцип ненасилия', 'война казалась близкой'] },
  },
  {
    id: 'split-with-congress-1940',
    year: 1940,
    label: 'Летом 1940 года разошёлся с Конгрессом по вопросу войны и ненасилия',
    critical: true,
    themes: ['conflict_duels', 'politics_public_pressure'],
    article: { all: [['летом 1940', 'привело к разрыву между ганди и конгрессом']] },
    extractor: { any: ['летом 1940', 'разрыву между ганди и конгрессом', 'войны'] },
  },
  {
    id: 'compromise-disarmament-formula',
    year: 1940,
    label: 'Согласился на компромиссную формулу Конгресса о ненасилии и разоружении',
    themes: ['politics_public_pressure'],
    article: { all: [['компромиссной', 'разоружение']] },
    extractor: { any: ['компромиссн', 'разоружение', 'согласие на формулировку'] },
  },
  {
    id: 'renewed-insistence-1941',
    year: 1941,
    label: 'В декабре 1941 года снова настаивал на полном соблюдении ненасилия',
    themes: ['politics_public_pressure'],
    article: { all: [['декабре 1941', 'полном соблюдении принципа ненасилия']] },
    extractor: { any: ['декабре 1941', 'полном соблюдении', 'ненасилия'] },
  },
  {
    id: 'another-split-with-congress',
    year: 1941,
    label: 'Новый спор с Конгрессом из-за войны и ненасилия',
    themes: ['conflict_duels', 'politics_public_pressure'],
    article: { all: [['это опять привело к расколу', 'конгресс']] },
    extractor: { any: ['опять привело к расколу', 'конгресс', '1941'] },
  },
  {
    id: 'accepted-war-if-free-india',
    year: 1941,
    label: 'Позже согласился на участие Конгресса в войне при условии свободы Индии',
    themes: ['politics_public_pressure'],
    article: { all: [['участие конгресса в войне', 'свободное государство']] },
    extractor: { any: ['участие конгресса в войне', 'свободное государство', 'согласился'] },
  },
  {
    id: 'aundh-experiment-1939',
    year: 1939,
    label: 'Добился провозглашения республики в Аундхе',
    critical: true,
    themes: ['service_career', 'politics_public_pressure'],
    article: { all: [['январе 1939', 'аундхский эксперимент']] },
    extractor: { any: ['аундх', 'республики', 'ноябрьская декларация'] },
  },
  {
    id: 'hindu-muslim-reconciliation',
    label: 'Старался примирить индусов и мусульман',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['старался примирить', 'индусов', 'мусульман']] },
    extractor: { any: ['примирить', 'индусов и мусульман', 'враждующие группировки'] },
  },
  {
    id: 'opposed-partition-1947',
    year: 1947,
    label: 'Крайне отрицательно отнёсся к разделу Британской Индии',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['крайне отрицательно отнёсся', 'разделению', '1947']] },
    extractor: { any: ['разделению', 'индия', 'пакистан', 'отрицательно отнёсся'] },
  },
  {
    id: 'communal-violence-disillusionment',
    year: 1947,
    label: 'Пережил тяжёлое разочарование из-за межрелигиозного насилия 1947 года',
    themes: ['losses', 'politics_public_pressure'],
    article: { all: [['1947 год', 'горьким разочарованием']] },
    extractor: { any: ['горьким разочарованием', '1947', 'межнациональные распри'] },
  },
  {
    id: 'fast-january-1948',
    year: 1948,
    label: 'В январе 1948 года начал голодовку ради прекращения межнациональных распрей',
    critical: true,
    themes: ['health', 'politics_public_pressure'],
    article: { all: [['январе 1948', 'прибегнул к голодовке']] },
    extractor: { any: ['январе 1948', 'голодовк', 'межнациональных распрей'] },
  },
  {
    id: 'leaders-promised-protect-muslims',
    year: 1948,
    label: 'Лидеры религиозных групп пообещали защищать мусульман и прекратить насилие в Дели',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['будем защищать жизнь', 'мусульман', 'дели']] },
    extractor: { any: ['защищать', 'мусульман', 'дели', 'совместное решение'] },
  },
  {
    id: 'extremist-opposition',
    label: 'Против него выступили индуистские экстремисты',
    themes: ['conflict_duels', 'politics_public_pressure'],
    article: { all: [['индуистские экстремисты', 'против']] },
    extractor: { any: ['индуистские экстремисты', 'хинду махасабха', 'выступали против'] },
  },
  {
    id: 'savarkar-conspiracy-1947',
    year: 1947,
    label: 'Саваркар в октябре 1947 года создал террористическую группу против Ганди',
    critical: true,
    themes: ['conflict_duels', 'politics_public_pressure'],
    article: { all: [['октябре 1947', 'саваркар', 'террористическую группу']] },
    extractor: { any: ['саваркар', 'октябре 1947', 'террористическ'] },
  },
  {
    id: 'assassination-1948',
    year: 1948,
    label: '30 января 1948 года был застрелен Натхурамом Годзе',
    critical: true,
    themes: ['losses', 'conflict_duels', 'health'],
    article: { all: [['30 января 1948', 'натхурам', 'застрелил']] },
    extractor: { any: ['30 января 1948', 'натхурам годзе', 'застрел'] },
  },
  {
    id: 'godse-apte-executed',
    year: 1948,
    label: 'Натхурам Годзе и Нарайян Апте были осуждены и казнены',
    themes: ['legacy', 'conflict_duels'],
    article: { all: [['натхурам годзе и нарайян апте', 'осуждены и казнены']] },
    extractor: { any: ['нарайян апте', 'осуждены и казнены', 'годзе'] },
  },
  {
    id: 'weekly-mauna',
    label: 'Еженедельно практиковал однодневную мауну',
    themes: ['health', 'legacy'],
    article: { all: [['еженедельно практиковал', 'мауну']] },
    extractor: { any: ['мауну', 'день молчания', 'ритуальное молчание'] },
  },
  {
    id: 'letters-to-hitler',
    label: 'Написал два письма Адольфу Гитлеру, пытаясь отговорить его от войны',
    themes: ['politics_public_pressure', 'legacy'],
    article: { all: [['два письма адольфу гитлеру', 'второй мировой войны']] },
    extractor: { any: ['два письма адольфу гитлеру', 'второй мировой войны', 'мой друг'] },
  },
];

const gandhiEditorialFactIds = new Set([
  'bania-vaishya-family',
  'father-divan',
  'mother-piety',
  'harilal-estrangement',
  'rights-of-indians-south-africa',
  'first-satyagraha',
  'bhagavad-gita-influence',
  'tolstoy-influence',
  'other-intellectual-influences',
  'tagore-mahatma-title',
  'disliked-mahatma-title',
  'tilak-successor',
  'boycott-british-goods',
  'led-inc-1921',
  'fight-untouchability',
  'harijans-term',
  'ashram-and-meals-with-harijans',
  'ambedkar-conflict',
  'fast-for-harijan-rights-1932',
  'charaka-sangh',
  'harijan-sevak-sangh',
  'brahmacharya-vow-1906',
  'translated-letter-to-a-hindu',
  'munich-crisis-test',
  'split-with-congress-1940',
  'accepted-war-if-free-india',
  'aundh-experiment-1939',
  'hindu-muslim-reconciliation',
  'opposed-partition-1947',
  'communal-violence-disillusionment',
  'fast-january-1948',
  'leaders-promised-protect-muslims',
  'savarkar-conspiracy-1947',
  'weekly-mauna',
  'letters-to-hitler',
]);

const gandhiEditorialFacts = gandhiFacts.filter((fact) => gandhiEditorialFactIds.has(fact.id));

const tolstoyFacts: BiographyExtractorBenchmarkFact[] = [
  // === Рождение и семья ===
  {
    id: 'birth-yasnaya-polyana',
    year: 1828,
    label: 'Рождение в Ясной Поляне, Тульская губерния',
    critical: true,
    themes: ['family_household'],
    article: { all: [['1828', 'ясная поляна']] },
    extractor: { any: ['ясная поляна', 'родился в ясной поляне', '1828'] },
  },
  {
    id: 'noble-origins',
    label: 'Происходил из знатного дворянского рода Толстых и Волконских',
    themes: ['family_household'],
    article: { all: [['толстых', 'волконск']] },
    extractor: { any: ['дворянского рода', 'граф', 'волконск', 'толстых'] },
  },
  {
    id: 'fourth-child',
    label: 'Был четвёртым ребёнком в семье',
    themes: ['family_household'],
    article: { all: [['четвёртым ребёнком']] },
    extractor: { any: ['четвёртым ребёнком', 'четвёртый ребёнок'] },
  },
  {
    id: 'mother-death',
    year: 1830,
    label: 'Смерть матери Марии Николаевны Волконской',
    critical: true,
    themes: ['losses', 'family_household'],
    article: { all: [['мать', 'мария николаевна', 'умерла']] },
    extractor: { any: ['смерть матери', 'мать умерла', 'мария николаевна'] },
  },
  {
    id: 'father-death',
    year: 1837,
    label: 'Смерть отца Николая Ильича Толстого',
    critical: true,
    themes: ['losses', 'family_household'],
    article: { all: [['отец', 'николай ильич', 'скончался']] },
    extractor: { any: ['смерть отца', 'отец скончался', 'николай ильич'] },
  },
  {
    id: 'guardian-aunt-osten-saken',
    label: 'Опекунство тётки А. И. Остен-Сакен',
    themes: ['family_household'],
    article: { all: [['остен-сакен', 'опек']] },
    extractor: { any: ['остен-сакен', 'опекунш', 'тётк'] },
  },
  // === Образование ===
  {
    id: 'kazan-university',
    year: 1844,
    label: 'Поступление в Казанский университет',
    critical: true,
    themes: ['education'],
    article: { all: [['казанский университет']] },
    extractor: { any: ['казанский университет', 'поступил в казанский'] },
  },
  {
    id: 'dropped-out-university',
    year: 1847,
    label: 'Ушёл из университета, не окончив курса',
    critical: true,
    themes: ['education'],
    article: { all: [['покинул', 'университет', 'не окончив']] },
    extractor: { any: ['не окончив курс', 'покинул университет', 'ушёл из университета', 'бросил университет'] },
  },
  // === Военная служба ===
  {
    id: 'caucasus-military',
    year: 1851,
    label: 'Отправился на Кавказ на военную службу',
    critical: true,
    themes: ['service_career', 'travel_moves_exile'],
    article: { all: [['кавказ', 'военн']] },
    extractor: { any: ['кавказ', 'военную службу', 'артиллерийск'] },
  },
  {
    id: 'crimean-war-sevastopol',
    year: 1854,
    label: 'Участие в Крымской войне и обороне Севастополя',
    critical: true,
    themes: ['service_career', 'conflict_duels'],
    article: { all: [['оборон', 'севастопол']] },
    extractor: { any: ['оборон', 'севастопол', 'крымск'] },
  },
  {
    id: 'sevastopol-stories',
    year: 1855,
    label: 'Севастопольские рассказы принесли литературную известность',
    critical: true,
    themes: ['creative_work', 'service_career'],
    article: { all: [['севастопольски', 'рассказ']] },
    extractor: { any: ['севастопольски', 'рассказ', 'литературн'] },
  },
  {
    id: 'military-retirement',
    year: 1856,
    label: 'Выход в отставку в чине поручика',
    themes: ['service_career'],
    article: { all: [['отставк', 'поручик']] },
    extractor: { any: ['отставк', 'поручик', 'вышел в отставку'] },
  },
  // === Литературный дебют ===
  {
    id: 'childhood-publication',
    year: 1852,
    label: 'Публикация повести «Детство» в «Современнике»',
    critical: true,
    themes: ['creative_work'],
    article: { all: [['детство', 'современник']] },
    extractor: { any: ['детство', 'современник', 'первая повесть'] },
  },
  // === Педагогическая деятельность ===
  {
    id: 'peasant-schools',
    year: 1859,
    label: 'Открытие школы для крестьянских детей в Ясной Поляне',
    critical: true,
    themes: ['education', 'service_career'],
    article: { all: [['школ', 'крестьянских детей', 'ясной поляне']] },
    extractor: { any: ['школ', 'крестьянских детей', 'педагогическ'] },
  },
  {
    id: 'azbuka-textbook',
    year: 1871,
    label: 'Издание «Азбуки» — учебника для обучения детей',
    themes: ['creative_work', 'education'],
    article: { all: [['азбук']] },
    extractor: { any: ['азбук', 'учебник', 'обучения детей'] },
  },
  // === Брак и семья ===
  {
    id: 'marriage-sofia-bers',
    year: 1862,
    label: 'Женитьба на Софье Андреевне Берс',
    critical: true,
    themes: ['romance', 'family_household'],
    article: { all: [['1862', 'софь', 'берс']] },
    extractor: { any: ['софья берс', 'женился на софье', 'софья андреевна', 'женитьба'] },
  },
  {
    id: 'thirteen-children',
    label: 'У Толстых родилось 13 детей',
    themes: ['children', 'family_household'],
    article: { all: [['13', 'детей']] },
    extractor: { any: ['13 детей', 'тринадцат', 'тринадцать детей'] },
  },
  // === Главные произведения ===
  {
    id: 'war-and-peace',
    year: 1863,
    label: 'Создание романа «Война и мир» (1863–1869)',
    critical: true,
    themes: ['creative_work'],
    article: { all: [['война и мир']] },
    extractor: { any: ['война и мир', 'роман-эпопе'] },
  },
  {
    id: 'anna-karenina',
    year: 1873,
    label: 'Создание романа «Анна Каренина» (1873–1877)',
    critical: true,
    themes: ['creative_work'],
    article: { all: [['анна каренина']] },
    extractor: { any: ['анна каренина'] },
  },
  {
    id: 'death-of-ivan-ilyich',
    year: 1886,
    label: 'Повесть «Смерть Ивана Ильича»',
    themes: ['creative_work'],
    article: { all: [['смерть ивана ильича']] },
    extractor: { any: ['смерть ивана ильича'] },
  },
  {
    id: 'kreutzer-sonata',
    year: 1889,
    label: 'Повесть «Крейцерова соната»',
    themes: ['creative_work'],
    article: { all: [['крейцерова соната']] },
    extractor: { any: ['крейцерова соната'] },
  },
  {
    id: 'resurrection-novel',
    year: 1899,
    label: 'Роман «Воскресение» — последний роман Толстого',
    critical: true,
    themes: ['creative_work'],
    article: { all: [['воскресение', 'роман']] },
    extractor: { any: ['воскресение', 'последний роман'] },
  },
  {
    id: 'hadji-murad',
    label: 'Повесть «Хаджи-Мурат» (опубликована посмертно)',
    themes: ['creative_work'],
    article: { all: [['хаджи-мурат']] },
    extractor: { any: ['хаджи-мурат', 'посмертно'] },
  },
  // === Духовный кризис и религиозные взгляды ===
  {
    id: 'spiritual-crisis',
    year: 1879,
    label: 'Глубокий духовный кризис конца 1870-х годов',
    critical: true,
    themes: ['losses', 'politics_public_pressure'],
    article: { all: [['духовн', 'кризис']] },
    extractor: { any: ['духовн', 'кризис', 'смысл жизни'] },
  },
  {
    id: 'confession-1882',
    year: 1882,
    label: 'Написание «Исповеди» — автобиографического произведения о духовных исканиях',
    critical: true,
    themes: ['creative_work', 'politics_public_pressure'],
    article: { all: [['исповедь']] },
    extractor: { any: ['исповедь', 'духовных исканий'] },
  },
  {
    id: 'excommunication',
    year: 1901,
    label: 'Отлучение от православной церкви Святейшим синодом',
    critical: true,
    themes: ['conflict_duels', 'politics_public_pressure'],
    article: { all: [['синод', 'отлуч']] },
    extractor: { any: ['отлуч', 'синод', 'церкв'] },
  },
  // === Общественная деятельность ===
  {
    id: 'vegetarianism',
    label: 'Переход к вегетарианству',
    themes: ['health', 'legacy'],
    article: { all: [['вегетариан']] },
    extractor: { any: ['вегетариан'] },
  },
  {
    id: 'manual-labor',
    label: 'Увлечение физическим трудом, пахал, шил сапоги',
    themes: ['health', 'legacy'],
    article: { all: [['физическ', 'труд']] },
    extractor: { any: ['физическ', 'труд', 'пахал', 'сапог'] },
  },
  {
    id: 'property-conflict-with-wife',
    year: 1883,
    label: 'Конфликт с женой из-за отказа от имущества и авторских прав',
    critical: true,
    themes: ['conflict_duels', 'family_household'],
    article: { all: [['имуществ', 'жен', 'ссор']] },
    extractor: { any: ['конфликт с женой', 'имуществ', 'авторских прав', 'ссор'] },
  },
  {
    id: 'famine-relief-1891',
    year: 1891,
    label: 'Организация помощи голодающим в 1891–1892 годах',
    themes: ['service_career', 'politics_public_pressure'],
    article: { all: [['голодающи', '1891']] },
    extractor: { any: ['голодающи', 'столовые', '1891'] },
  },
  {
    id: 'support-dukhobors',
    year: 1898,
    label: 'Помощь духоборам в переселении в Канаду',
    themes: ['service_career', 'politics_public_pressure'],
    article: { all: [['духобор', 'канад']] },
    extractor: { any: ['духобор', 'канад', 'переселени'] },
  },
  // === Окружение и влияние ===
  {
    id: 'chertkov-relationship',
    label: 'Близкие отношения с Владимиром Чертковым — главным единомышленником',
    themes: ['friends_network'],
    article: { all: [['чертков']] },
    extractor: { any: ['чертков', 'единомышленник', 'ближайший друг'] },
  },
  {
    id: 'secret-testament',
    year: 1910,
    label: 'Тайное завещание — все сочинения становились общественным достоянием',
    themes: ['family_household', 'legacy'],
    article: { all: [['завещани', 'общественным достоянием']] },
    extractor: { any: ['завещани', 'общественным достоянием', 'авторские права'] },
  },
  {
    id: 'influence-on-gandhi',
    label: 'Влияние на Ганди и переписка с ним',
    themes: ['friends_network', 'legacy'],
    article: { all: [['ганди']] },
    extractor: { any: ['ганди', 'переписк'] },
  },
  {
    id: 'nobel-nominations',
    label: 'Номинации на Нобелевскую премию, от которых отказался',
    themes: ['legacy'],
    article: { all: [['нобелевск']] },
    extractor: { any: ['нобелевск', 'отказ'] },
  },
  // === Ведение дневника ===
  {
    id: 'lifelong-diary',
    label: 'Вёл дневник на протяжении всей жизни',
    themes: ['creative_work', 'legacy'],
    article: { all: [['дневник']] },
    extractor: { any: ['дневник', 'записи'] },
  },
  // === Поездка в Европу ===
  {
    id: 'paris-guillotine',
    year: 1857,
    label: 'Потрясение от публичной казни на гильотине в Париже',
    themes: ['travel_moves_exile', 'politics_public_pressure'],
    article: { all: [['париж', 'гильотин']] },
    extractor: { any: ['гильотин', 'казн', 'париж'] },
  },
  // === Смерть брата ===
  {
    id: 'brother-nikolai-death',
    year: 1860,
    label: 'Смерть старшего брата Николая от туберкулёза',
    themes: ['losses', 'family_household'],
    article: { all: [['брат', 'николай', 'умер']] },
    extractor: { any: ['брат николай', 'смерть брата', 'туберкулёз'] },
  },
  // === Назначение мировым посредником ===
  {
    id: 'justice-of-peace',
    year: 1861,
    label: 'Назначение мировым посредником после отмены крепостного права',
    themes: ['service_career', 'politics_public_pressure'],
    article: { all: [['мировым посредником']] },
    extractor: { any: ['мировым посредником', 'крепостного права'] },
  },
  // === Обыск ===
  {
    id: 'police-search',
    year: 1862,
    label: 'Обыск жандармов в Ясной Поляне',
    themes: ['conflict_duels', 'politics_public_pressure'],
    article: { all: [['обыск', 'ясной поляне']] },
    extractor: { any: ['обыск', 'жандарм', 'типографи'] },
  },
  // === Уход и смерть ===
  {
    id: 'departure-yasnaya-polyana',
    year: 1910,
    label: 'Тайный уход из Ясной Поляны',
    critical: true,
    themes: ['travel_moves_exile', 'family_household', 'losses'],
    article: { all: [['тайно', 'покинул', 'ясную поляну']] },
    extractor: { any: ['тайно покинул', 'ушёл из ясной поляны', 'уход из ясной поляны'] },
  },
  {
    id: 'death-astapovo',
    year: 1910,
    label: 'Смерть на станции Астапово в возрасте 82 лет',
    critical: true,
    themes: ['health', 'losses'],
    article: { all: [['астапово', '1910']] },
    extractor: { any: ['астапово', 'скончался', 'смерть на станции'] },
  },
  // === Болезнь в Крыму ===
  {
    id: 'illness-crimea-1902',
    year: 1902,
    label: 'Тяжёлая болезнь в Крыму — воспаление лёгких и тиф',
    themes: ['health'],
    article: { all: [['крым', 'болезн']] },
    extractor: { any: ['крым', 'воспаление лёгких', 'тиф', 'болезн'] },
  },
  // === 80-летний юбилей ===
  {
    id: 'jubilee-80',
    year: 1908,
    label: 'Широкое празднование 80-летия писателя',
    themes: ['legacy'],
    article: { all: [['80-лети']] },
    extractor: { any: ['80-лети', 'юбиле'] },
  },
  // === Толстовство ===
  {
    id: 'tolstoyanism',
    label: 'Основание религиозно-нравственного течения — толстовства',
    themes: ['legacy', 'politics_public_pressure'],
    article: { all: [['толстовств']] },
    extractor: { any: ['толстовств', 'непротивлени', 'ненасили'] },
  },
];

const tolstoyEditorialFactIds = new Set([
  'noble-origins',
  'fourth-child',
  'guardian-aunt-osten-saken',
  'dropped-out-university',
  'sevastopol-stories',
  'military-retirement',
  'childhood-publication',
  'peasant-schools',
  'azbuka-textbook',
  'thirteen-children',
  'death-of-ivan-ilyich',
  'kreutzer-sonata',
  'hadji-murad',
  'confession-1882',
  'vegetarianism',
  'manual-labor',
  'property-conflict-with-wife',
  'famine-relief-1891',
  'support-dukhobors',
  'chertkov-relationship',
  'secret-testament',
  'influence-on-gandhi',
  'nobel-nominations',
  'lifelong-diary',
  'paris-guillotine',
  'brother-nikolai-death',
  'justice-of-peace',
  'police-search',
  'illness-crimea-1902',
  'jubilee-80',
  'tolstoyanism',
]);

const tolstoyEditorialFacts = tolstoyFacts.filter((fact) => tolstoyEditorialFactIds.has(fact.id));

export const biographyExtractorBenchmarks: Record<string, BiographyExtractorBenchmark> = {
  gandhi: {
    id: 'gandhi',
    subject: 'Махатма Ганди',
    sourceUrl: 'https://ru.wikipedia.org/wiki/Махатма_Ганди',
    facts: gandhiFacts,
  },
  'gandhi-editorial': {
    id: 'gandhi-editorial',
    subject: 'Махатма Ганди — editorial facts',
    sourceUrl: 'https://ru.wikipedia.org/wiki/Махатма_Ганди',
    facts: gandhiEditorialFacts,
  },
  tolstoy: {
    id: 'tolstoy',
    subject: 'Лев Толстой',
    sourceUrl: 'https://ru.wikipedia.org/wiki/Толстой,_Лев_Николаевич',
    facts: tolstoyFacts,
  },
  'tolstoy-editorial': {
    id: 'tolstoy-editorial',
    subject: 'Лев Толстой — editorial facts',
    sourceUrl: 'https://ru.wikipedia.org/wiki/Толстой,_Лев_Николаевич',
    facts: tolstoyEditorialFacts,
  },
};
