export type BiographyBenchmarkMatcher = {
  any?: string[];
  all?: string[][];
};

export type BiographyBenchmarkFact = {
  id: string;
  year?: number;
  label: string;
  critical?: boolean;
  themes?: string[];
  article?: BiographyBenchmarkMatcher;
  timeline?: BiographyBenchmarkMatcher;
};

export type BiographyBenchmark = {
  id: string;
  subject: string;
  sourceUrl: string;
  facts: BiographyBenchmarkFact[];
};

const elizabethIIFacts: BiographyBenchmarkFact[] = [
  {
    id: 'birth-mayfair',
    year: 1926,
    label: 'Рождение в Мейфэре',
    critical: true,
    themes: ['family_household'],
    article: { all: [['родилась', 'мейфэр']] },
    timeline: { any: ['рождение', 'родилась', 'мейфэр'] },
  },
  {
    id: 'york-family-and-lilibet',
    year: 1926,
    label: 'Дочь герцога и герцогини Йоркских, домашнее имя Лилибет',
    themes: ['family_household'],
    article: { all: [['герцога йоркского', 'лилибет']] },
    timeline: { any: ['йоркск', 'лилибет'] },
  },
  {
    id: 'margaret-born',
    year: 1930,
    label: 'Рождение сестры Маргарет',
    themes: ['family_household'],
    article: { all: [['маргарет', '1930']] },
    timeline: { all: [['маргарет', 'сестр']] },
  },
  {
    id: 'home-education',
    year: 1931,
    label: 'Домашнее образование',
    themes: ['education'],
    article: { all: [['домашнее образование', 'мэрион кроуфорд']] },
    timeline: { any: ['домашнее образование', 'мэрион кроуфорд'] },
  },
  {
    id: 'horses-and-riding',
    year: 1932,
    label: 'Увлечение лошадьми и верховой ездой',
    themes: ['hobby'],
    article: { all: [['лошадьми', 'верховой ездой']] },
    timeline: { any: ['лошад', 'верхов'] },
  },
  {
    id: 'heir-after-abdication',
    year: 1936,
    label: 'Стала наследницей после отречения Эдуарда VIII',
    critical: true,
    themes: ['service_career'],
    article: { all: [['отречься', 'наследницей трона']] },
    timeline: { any: ['наследниц', 'отречен', 'эдуард viii'] },
  },
  {
    id: 'move-to-buckingham',
    year: 1936,
    label: 'Переезд в Букингемский дворец',
    themes: ['travel_moves_exile'],
    article: { all: [['букингемский дворец', 'переехала']] },
    timeline: { all: [['букингем', 'переезд']] },
  },
  {
    id: 'war-at-windsor',
    year: 1939,
    label: 'Во время войны жила в Виндзорском замке',
    themes: ['travel_moves_exile'],
    article: { all: [['виндзорском замке', 'войны']] },
    timeline: { any: ['виндзор', 'войн'] },
  },
  {
    id: 'radio-broadcast-1940',
    year: 1940,
    label: 'Первое радиообращение к детям во время войны',
    critical: true,
    themes: ['service_career'],
    article: { all: [['детский час', 'впервые выступила по радио']] },
    timeline: { any: ['радиообращ', 'детский час', 'по радио'] },
  },
  {
    id: 'first-solo-public-engagement',
    year: 1943,
    label: 'Первое самостоятельное публичное появление',
    themes: ['service_career'],
    article: { all: [['первое самостоятельное появление', 'гвардейских гренадеров']] },
    timeline: { any: ['первое самостоятельное', 'гренадер'] },
  },
  {
    id: 'counsellor-of-state',
    year: 1944,
    label: 'Стала государственным советником',
    themes: ['service_career'],
    article: { all: [['государственных советников', '1944']] },
    timeline: { any: ['государственн', 'советник'] },
  },
  {
    id: 'ats-service-first-royal-woman',
    year: 1945,
    label: 'Служба во Вспомогательной территориальной службе',
    critical: true,
    themes: ['service_career'],
    article: { any: ['вспомогательную территориальную службу', 'первая женщина из королевской семьи'] },
    timeline: { any: ['вспомогательн', 'ats', 'механик', 'санитарного автомобиля'] },
  },
  {
    id: 'south-africa-tour',
    year: 1947,
    label: 'Поездка в Южную Африку',
    themes: ['travel_moves_exile'],
    article: { all: [['поездке по южной африке', '1947']] },
    timeline: { any: ['южной африк', 'африке'] },
  },
  {
    id: 'lifelong-service-vow',
    year: 1947,
    label: 'Обещание посвятить жизнь служению',
    critical: true,
    themes: ['service_career'],
    article: { all: [['вся моя жизнь', 'будет посвящена служению']] },
    timeline: { any: ['посвятить жизнь', 'служению', 'обещан'] },
  },
  {
    id: 'met-philip-dartmouth',
    year: 1939,
    label: 'Знакомство и сближение с Филиппом',
    themes: ['romance'],
    article: { all: [['дартмуте', 'филипп', 'полюбила']] },
    timeline: { any: ['филипп', 'дартмут', 'познаком'] },
  },
  {
    id: 'engagement-1947',
    year: 1947,
    label: 'Объявление помолвки с Филиппом',
    themes: ['romance'],
    article: { all: [['помолвке', '9 июля 1947']] },
    timeline: { any: ['помолв', 'филипп'] },
  },
  {
    id: 'philip-duke-before-wedding',
    year: 1947,
    label: 'Филипп получил титул герцога Эдинбургского',
    themes: ['romance'],
    article: { all: [['герцога эдинбургского', 'накануне свадьбы']] },
    timeline: { any: ['герцога эдинбургского', 'филипп получил титул'] },
  },
  {
    id: 'wedding-1947',
    year: 1947,
    label: 'Свадьба в Вестминстерском аббатстве',
    critical: true,
    themes: ['family_household'],
    article: { all: [['вестминстерском аббатстве', '20 ноября 1947']] },
    timeline: { any: ['свадьб', 'вестминстер'] },
  },
  {
    id: 'paris-1948',
    year: 1948,
    label: 'Первый официальный зарубежный визит в Париж',
    themes: ['travel_moves_exile'],
    article: { all: [['официальный зарубежный визит', 'париж']] },
    timeline: { any: ['париж', 'первый официальный зарубежный визит'] },
  },
  {
    id: 'charles-born',
    year: 1948,
    label: 'Рождение принца Чарльза',
    critical: true,
    themes: ['children'],
    article: { all: [['родился старший сын принц чарльз', '14 ноября 1948']] },
    timeline: { any: ['чарльз', 'родил'] },
  },
  {
    id: 'anne-born',
    year: 1950,
    label: 'Рождение принцессы Анны',
    themes: ['children'],
    article: { all: [['принцесса анна', '15 августа 1950']] },
    timeline: { any: ['анна', 'родил'] },
  },
  {
    id: 'stand-in-for-george-and-truman-trip',
    year: 1951,
    label: 'Замещала больного Георга VI и посетила Канаду и США',
    themes: ['service_career'],
    article: { all: [['здоровье георга vi ухудшилось', 'гарри трумэном']] },
    timeline: { any: ['георга vi ухудшилось', 'трумэн', 'канаду и сша'] },
  },
  {
    id: 'commonwealth-tour-cut-short',
    year: 1952,
    label: 'Тур по странам Содружества прервался смертью короля',
    themes: ['travel_moves_exile'],
    article: { all: [['визитом по странам содружества', 'прерван смертью короля']] },
    timeline: { any: ['прерван смертью короля', 'тур по содружеству'] },
  },
  {
    id: 'accession-in-kenya',
    year: 1952,
    label: 'Восшествие на престол в Кении',
    critical: true,
    themes: ['service_career'],
    article: { all: [['провозглашена королевой', 'кении']] },
    timeline: { any: ['восшествие на престол', 'кении', 'сагана'] },
  },
  {
    id: 'regnal-name-and-proclamation',
    year: 1952,
    label: 'Выбрала тронное имя и приняла присягу Тайного совета',
    themes: ['service_career'],
    article: { all: [['предпочла оставаться елизаветой', 'тайного совета']] },
    timeline: { any: ['тронное имя', 'тайного совета', 'предпочла оставаться елизаветой'] },
  },
  {
    id: 'windsor-house-proclamation',
    year: 1952,
    label: 'Прокламация о доме Виндзоров',
    themes: ['family_household'],
    article: { all: [['9 апреля 1952', 'дому виндзоров']] },
    timeline: { any: ['дом виндзоров', 'прокламац'] },
  },
  {
    id: 'coronation-televised',
    year: 1953,
    label: 'Коронация, впервые показанная по телевидению',
    critical: true,
    themes: ['service_career'],
    article: { all: [['коронации елизаветы ii', 'первая коронация', 'телевидению']] },
    timeline: { any: ['коронац', 'телевиз'] },
  },
  {
    id: 'portsmouth-naval-review',
    year: 1953,
    label: 'Военно-морской парад в Портсмуте',
    themes: ['service_career'],
    article: { all: [['портсмуте', 'военно-морской парад']] },
    timeline: { any: ['портсмут', 'военно-морской парад'] },
  },
  {
    id: 'commonwealth-tour-and-australia-nz',
    year: 1953,
    label: 'Шестимесячное турне по Содружеству и миру',
    critical: true,
    themes: ['travel_moves_exile'],
    article: { all: [['шестимесячное турне', 'австралию и новую зеландию']] },
    timeline: { any: ['шестимесячное турне', 'содружеств', 'австралию и новую зеландию'] },
  },
  {
    id: 'khrushchev-bulganin-visit',
    year: 1956,
    label: 'Приём Хрущёва и Булганина',
    themes: ['politics_public_pressure'],
    article: { all: [['хрущёва', 'булганина']] },
    timeline: { any: ['хрущев', 'булганин'] },
  },
  {
    id: 'macmillan-appointed-after-eden',
    year: 1957,
    label: 'Назначила Гарольда Макмиллана после отставки Идена',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['отставки премьер-министра сэра энтони идена', 'гарольд макмиллан']] },
    timeline: { any: ['макмиллан', 'иден'] },
  },
  {
    id: 'first-tv-christmas-message',
    year: 1957,
    label: 'Первое рождественское поздравление по телевидению',
    critical: true,
    themes: ['service_career'],
    article: { all: [['рождеством по телевидению', '25 декабря 1957']] },
    timeline: { any: ['рождествен', 'телевиден'] },
  },
  {
    id: 'mountbatten-windsor-surname',
    year: 1960,
    label: 'Ввела фамилию Маунтбеттен-Виндзор для потомков',
    themes: ['family_household'],
    article: { all: [['маунтбеттен-виндзоры', '8 февраля 1960']] },
    timeline: { any: ['маунтбеттен-виндзор', 'личную фамилию'] },
  },
  {
    id: 'andrew-born',
    year: 1960,
    label: 'Рождение принца Эндрю',
    themes: ['children'],
    article: { all: [['19 февраля', 'принц эндрю']] },
    timeline: { any: ['эндрю', 'родил'] },
  },
  {
    id: '1961-world-tour-including-ghana',
    year: 1961,
    label: 'Крупное зарубежное турне, включая Гану',
    themes: ['travel_moves_exile'],
    article: { all: [['в 1961 году', 'гану']] },
    timeline: { any: ['ган', 'мировое турне', 'крупное зарубежное турне'] },
  },
  {
    id: 'kennedy-visit',
    year: 1961,
    label: 'Приём Джона и Жаклин Кеннеди',
    themes: ['politics_public_pressure'],
    article: { all: [['джона кеннеди', 'жаклин']] },
    timeline: { any: ['кеннеди', 'жаклин'] },
  },
  {
    id: 'gagarin-lunch',
    year: 1961,
    label: 'Приём Юрия Гагарина',
    themes: ['politics_public_pressure'],
    article: { all: [['юрия гагарина', 'ланч']] },
    timeline: { any: ['гагарин'] },
  },
  {
    id: 'douglas-home-appointed',
    year: 1963,
    label: 'Назначила премьера Александра Дуглас-Хьюма',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['макмиллана', 'александра дуглас-хьюма']] },
    timeline: { any: ['дуглас-хьюм', 'макмиллан'] },
  },
  {
    id: 'edward-born',
    year: 1964,
    label: 'Рождение принца Эдварда',
    themes: ['children'],
    article: { all: [['10 марта 1964', 'принц эдвард']] },
    timeline: { any: ['эдвард', 'родил'] },
  },
  {
    id: 'royal-family-doc-and-charles-investiture',
    year: 1969,
    label: 'Фильм Royal Family и инвеститура Чарльза',
    critical: true,
    themes: ['service_career'],
    article: { all: [['королевская семья', 'инвеституру наследника']] },
    timeline: { any: ['royal family', 'королевская семья', 'инвеститур', 'чарльза'] },
  },
  {
    id: 'royal-walkabout',
    year: 1970,
    label: 'Ввела практику royal walkabout',
    critical: true,
    themes: ['service_career'],
    article: { all: [['royal walkabout', 'австралии и новой зеландии']] },
    timeline: { any: ['walkabout', 'королевскую прогулку'] },
  },
  {
    id: 'wilson-appointed-1974',
    year: 1974,
    label: 'Назначила Гарольда Вильсона после подвешенных выборов',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['1974', 'гарольда вильсона']] },
    timeline: { any: ['гарольд вильсон', 'подвешенн', '1974'] },
  },
  {
    id: 'australia-constitutional-crisis-1975',
    year: 1975,
    label: 'Кризис в Австралии и отказ отменить отставку Уитлэма',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['австралии', 'уитлэма']] },
    timeline: { any: ['уитлэм', 'австрал', 'кризис'] },
  },
  {
    id: 'first-email-1976',
    year: 1976,
    label: 'Стала первым главой государства, отправившим email',
    themes: ['service_career'],
    article: { all: [['электронную почту', 'arpanet']] },
    timeline: { any: ['электронную почту', 'email', 'arpanet'] },
  },
  {
    id: 'montreal-olympics-1976',
    year: 1976,
    label: 'Открыла Олимпиаду в Монреале',
    themes: ['service_career'],
    article: { all: [['олимпийские игры в монреале', 'как королева канады']] },
    timeline: { any: ['монреал', 'олимпиад'] },
  },
  {
    id: 'silver-jubilee-1977',
    year: 1977,
    label: 'Серебряный юбилей правления',
    critical: true,
    themes: ['service_career'],
    article: { all: [['серебряный юбилей', '25-летие']] },
    timeline: { any: ['серебряный юбилей', '25-летие'] },
  },
  {
    id: 'thatcher-pm-1979',
    year: 1979,
    label: 'Маргарет Тэтчер стала премьер-министром',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['маргарет тэтчер', '3 мая 1979']] },
    timeline: { any: ['маргарет тэтчер', 'премьер-министр'] },
  },
  {
    id: 'mountbatten-assassination-1979',
    year: 1979,
    label: 'Убийство Луиса Маунтбеттена IRA',
    critical: true,
    themes: ['losses'],
    article: { all: [['луиса маунтбеттена', 'ирландской республиканской армии']] },
    timeline: { any: ['маунтбеттен', 'ira', 'ирландск'] },
  },
  {
    id: 'charles-diana-wedding-1981',
    year: 1981,
    label: 'Свадьба Чарльза и Дианы',
    critical: true,
    themes: ['family_household'],
    article: { all: [['29 июля 1981', 'дианы спенсер']] },
    timeline: { any: ['чарльз', 'диан', 'свадьб'] },
  },
  {
    id: 'trooping-shooting-1981',
    year: 1981,
    label: 'Выстрелы во время Trooping the Colour',
    critical: true,
    themes: ['conflict_duels'],
    article: { all: [['шесть выстрелов', 'в сторону елизаветы ii']] },
    timeline: { any: ['выстрел', 'trooping', 'официального дня рождения'] },
  },
  {
    id: 'william-born-1982',
    year: 1982,
    label: 'Рождение принца Уильяма',
    themes: ['children'],
    article: { all: [['принц уильям', '21 июня 1982']] },
    timeline: { any: ['уильям', 'родил'] },
  },
  {
    id: 'papal-visit-1982',
    year: 1982,
    label: 'Приняла Иоанна Павла II в Великобритании',
    themes: ['politics_public_pressure'],
    article: { all: [['иоанна павла ii', 'великобританию']] },
    timeline: { any: ['иоанна павла', 'пап'] },
  },
  {
    id: 'harry-born-1984',
    year: 1984,
    label: 'Рождение принца Гарри',
    themes: ['children'],
    article: { all: [['принц гарри', '15 сентября 1984']] },
    timeline: { any: ['гарри', 'родил'] },
  },
  {
    id: 'yemen-evacuation-1986',
    year: 1986,
    label: 'Эвакуация людей из Йемена на яхте Britannia',
    critical: true,
    themes: ['service_career'],
    article: { all: [['бывшей британской колонии аден', '1068 человек эвакуированных']] },
    timeline: { any: ['йемен', 'эвакуац', '1068'] },
  },
  {
    id: 'china-visit-1986',
    year: 1986,
    label: 'Первый визит британского монарха в Китай',
    critical: true,
    themes: ['travel_moves_exile'],
    article: { all: [['первое посещение китая британским монархом', 'дэн сяопином']] },
    timeline: { any: ['китай', 'дэн сяопин', 'первое посещение'] },
  },
  {
    id: 'gorbachev-visit-1989',
    year: 1989,
    label: 'Приём Михаила Горбачёва',
    themes: ['politics_public_pressure'],
    article: { all: [['михаила горбачёва', '7 апреля 1989']] },
    timeline: { any: ['горбач', 'раиса'] },
  },
  {
    id: 'thatcher-resignation-1990',
    year: 1990,
    label: 'Отставка Маргарет Тэтчер',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['маргарет тэтчер объявила о своём уходе', '1990']] },
    timeline: { any: ['тэтчер', 'отставк'] },
  },
  {
    id: 'congress-speech-1991',
    year: 1991,
    label: 'Выступление в Конгрессе США',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['палат конгресса сша', '1991']] },
    timeline: { any: ['конгресс', 'сша'] },
  },
  {
    id: 'annus-horribilis-1992',
    year: 1992,
    label: 'Annus horribilis',
    critical: true,
    themes: ['family_household'],
    article: { all: [['annus horribilis', 'ужасным годом']] },
    timeline: { any: ['annus horribilis', 'ужасный год'] },
  },
  {
    id: 'windsor-fire-1992',
    year: 1992,
    label: 'Пожар в Виндзорском замке',
    critical: true,
    themes: ['losses'],
    article: { all: [['пожар в виндзорском замке', '20 ноября']] },
    timeline: { any: ['виндзор', 'пожар'] },
  },
  {
    id: 'charles-diana-separation-1992',
    year: 1992,
    label: 'Объявлено о расставании Чарльза и Дианы',
    critical: true,
    themes: ['family_household'],
    article: { all: [['раздельном проживании', 'принца чарльза и принцессы дианы']] },
    timeline: { any: ['чарльз', 'диан', 'расставан', 'раздельном проживании'] },
  },
  {
    id: 'eurotunnel-opening-1994',
    year: 1994,
    label: 'Открытие тоннеля под Ла-Маншем',
    themes: ['service_career'],
    article: { all: [['открытии тоннеля под проливом ла-манш', 'миттеран']] },
    timeline: { any: ['ла-манш', 'евротуннел', 'миттеран'] },
  },
  {
    id: 'russia-state-visit-1994',
    year: 1994,
    label: 'Государственный визит в Россию',
    critical: true,
    themes: ['travel_moves_exile'],
    article: { all: [['государственным визитом посетила россию', 'борисом ельциным']] },
    timeline: { any: ['росси', 'ельцин', 'москв', 'санкт-петербург'] },
  },
  {
    id: 'diana-death-backlash-1997',
    year: 1997,
    label: 'Критика после гибели принцессы Дианы',
    critical: true,
    themes: ['losses'],
    article: { all: [['смерть принцессы дианы', 'гнев']] },
    timeline: { any: ['диан', 'критик', 'гнев', 'гибел'] },
  },
  {
    id: 'golden-jubilee-and-losses-2002',
    year: 2002,
    label: 'Золотой юбилей на фоне смерти Маргарет и королевы-матери',
    critical: true,
    themes: ['losses'],
    article: { all: [['золотой юбилей', 'принцесса маргарет', 'королева-мать']] },
    timeline: { any: ['золотой юбилей', 'маргарет', 'королева-мать'] },
  },
  {
    id: 'oldest-british-monarch-2007',
    year: 2007,
    label: 'Стала старейшим британским монархом',
    themes: ['legacy'],
    article: { all: [['20 декабря 2007', 'старейшим британским монархом']] },
    timeline: { any: ['старейшим британским монархом', '2007'] },
  },
  {
    id: 'ireland-visit-2011',
    year: 2011,
    label: 'Исторический государственный визит в Ирландию',
    critical: true,
    themes: ['travel_moves_exile'],
    article: { all: [['ирланди', 'государственный визит']] },
    timeline: { any: ['ирланди', 'исторический визит'] },
  },
  {
    id: 'diamond-jubilee-2012',
    year: 2012,
    label: 'Бриллиантовый юбилей правления',
    critical: true,
    themes: ['service_career'],
    article: { all: [['алмазная королева', '60-летию восшествия']] },
    timeline: { any: ['бриллиантов', 'алмазн', '60-лет'] },
  },
  {
    id: 'james-bond-olympics-2012',
    year: 2012,
    label: 'Олимпийское камео с Джеймсом Бондом',
    critical: true,
    themes: ['service_career'],
    article: { all: [['джеймса бонда', 'олимпийских игр в лондоне']] },
    timeline: { any: ['джеймс бонд', 'олимпиад', 'дэниел крейг'] },
  },
  {
    id: 'longest-reigning-british-monarch-2015',
    year: 2015,
    label: 'Стала самым долгоправящим британским монархом',
    critical: true,
    themes: ['legacy'],
    article: { all: [['самым долгоправящим', 'британской истории']] },
    timeline: { any: ['долгоправящ', 'обогнав', 'виктори'] },
  },
  {
    id: 'platinum-wedding-2017',
    year: 2017,
    label: 'Платиновая свадьба с Филиппом',
    themes: ['family_household'],
    article: { all: [['платиновую свадьбу', '20 ноября 2017']] },
    timeline: { any: ['платиновую свадьбу', '70 лет брака'] },
  },
  {
    id: 'philip-death-2021',
    year: 2021,
    label: 'Смерть принца Филиппа',
    critical: true,
    themes: ['losses'],
    article: { all: [['9 апреля 2021', 'скончался муж королевы принц филипп']] },
    timeline: { any: ['смерть мужа', 'принц филипп', 'филипп'] },
  },
  {
    id: 'nhs-george-cross-2021',
    year: 2021,
    label: 'Наградила NHS Крестом Георга',
    themes: ['service_career'],
    article: { any: ['национальной службы здравоохранения', 'крестом георга', 'nhs будет награждена'] },
    timeline: { any: ['nhs', 'крестом георга'] },
  },
  {
    id: 'barbados-republic-2021',
    year: 2021,
    label: 'Барбадос стал республикой',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['барбадос', 'стал республикой']] },
    timeline: { any: ['барбадос', 'республикой'] },
  },
  {
    id: '70-years-on-throne-2022',
    year: 2022,
    label: '70 лет на престоле',
    critical: true,
    themes: ['legacy'],
    article: { all: [['70 лет', '6 февраля 2022']] },
    timeline: { any: ['70 лет', 'платинов', 'первым монархом'] },
  },
  {
    id: 'covid-2022',
    year: 2022,
    label: 'Перенесла COVID-19',
    themes: ['health'],
    article: { all: [['covid-19', '20 февраля 2022']] },
    timeline: { any: ['covid', 'коронавирус'] },
  },
  {
    id: 'windsor-permanent-residence-2022',
    year: 2022,
    label: 'Сделала Виндзор постоянной резиденцией',
    themes: ['travel_moves_exile'],
    article: { all: [['виндзорский замок своей постоянной резиденцией', '6 марта']] },
    timeline: { any: ['виндзорский замок', 'постоянной резиденц'] },
  },
  {
    id: 'liz-truss-appointment-2022',
    year: 2022,
    label: 'Назначила Лиз Трасс премьер-министром',
    critical: true,
    themes: ['politics_public_pressure'],
    article: { all: [['лиз трасс', 'приняла отставку бориса джонсона']] },
    timeline: { any: ['лиз трасс', 'бориса джонсона'] },
  },
  {
    id: 'death-balmoral-2022',
    year: 2022,
    label: 'Смерть в замке Балморал',
    critical: true,
    themes: ['health'],
    article: { all: [['8 сентября 2022', 'балморал']] },
    timeline: { any: ['смерть', 'балморал'] },
  },
  {
    id: 'charles-king-and-funeral-2022',
    year: 2022,
    label: 'Карл III вступил на престол, прошли государственные похороны',
    critical: true,
    themes: ['legacy'],
    article: { all: [['карлом iii', 'государственные похороны']] },
    timeline: { any: ['карл iii', 'похорон', 'вестминстерском аббатстве'] },
  },
];

export const biographyBenchmarks: Record<string, BiographyBenchmark> = {
  'elizabeth-ii': {
    id: 'elizabeth-ii',
    subject: 'Елизавета II',
    sourceUrl: 'https://ru.wikipedia.org/wiki/Елизавета_II',
    facts: elizabethIIFacts,
  },
};
