import { Timestamp } from 'firebase-admin/firestore';
import {
  buildTranscriptFullText,
  buildTranscriptPreview,
  buildVideoTranscriptStoragePath,
  getTranscriptDurationMs,
} from '../../src/lib/videoTranscripts';
import {
  VIDEO_TRANSCRIPT_VERSION,
  type VideoTranscriptStoragePayload,
} from '../../src/types/videoTranscripts';
import type {
  ImportStatus,
  TranscriptImportResult,
  TranscriptImportTarget,
} from './videoTranscriptImportTypes';

export function buildTranscriptPendingDoc(youtubeVideoId: string, now: Timestamp) {
  return {
    youtubeVideoId,
    source: 'youtube' as const,
    status: 'pending' as const,
    updatedAt: now,
    lastCheckedAt: now,
  };
}

export function buildTranscriptAvailablePayload(
  target: TranscriptImportTarget,
  transcript: TranscriptImportResult,
  now: Timestamp
) {
  const fullText = buildTranscriptFullText(transcript.segments);
  const durationMs = getTranscriptDurationMs(transcript.segments);
  const storagePath = buildVideoTranscriptStoragePath(
    target.youtubeVideoId,
    VIDEO_TRANSCRIPT_VERSION
  );

  const storagePayload: VideoTranscriptStoragePayload = {
    youtubeVideoId: target.youtubeVideoId,
    version: VIDEO_TRANSCRIPT_VERSION,
    source: 'youtube',
    language: transcript.language,
    languageName: null,
    isAutoGenerated: null,
    fetchedAt: new Date().toISOString(),
    durationMs,
    fullText,
    segments: transcript.segments,
  };

  const docPayload = {
    availableLanguages: transcript.availableLanguages,
    durationMs,
    errorCode: null,
    errorMessage: null,
    fetchedAt: now,
    fullTextPreview: buildTranscriptPreview(fullText),
    isAutoGenerated: null,
    language: transcript.language,
    languageName: null,
    lastCheckedAt: now,
    segmentCount: transcript.segments.length,
    source: 'youtube',
    status: 'available' as const,
    storagePath,
    textLength: fullText.length,
    updatedAt: now,
    version: VIDEO_TRANSCRIPT_VERSION,
    youtubeVideoId: target.youtubeVideoId,
  };

  return {
    docPayload,
    storagePath,
    storagePayload,
  };
}

export function buildTranscriptFailedDoc(
  youtubeVideoId: string,
  status: ImportStatus,
  errorCode: string,
  errorMessage: string,
  availableLanguages: string[],
  now: Timestamp
) {
  return {
    availableLanguages,
    durationMs: null,
    errorCode,
    errorMessage,
    fullTextPreview: null,
    language: null,
    languageName: null,
    lastCheckedAt: now,
    segmentCount: 0,
    source: 'youtube',
    status,
    storagePath: null,
    textLength: 0,
    updatedAt: now,
    version: VIDEO_TRANSCRIPT_VERSION,
    youtubeVideoId,
  };
}
