import { buildTranscriptFullText, buildTranscriptPreview, buildVideoTranscriptStoragePath, getTranscriptDurationMs } from "./helpers.js";
import { VIDEO_TRANSCRIPT_VERSION, } from "./schema.js";
import { buildAvailableRetryFields, buildEmptyTranscriptDoc, buildFailedRetryFields, } from "./retry.js";
export function buildTranscriptPendingDoc(youtubeVideoId, now) {
    return {
        ...buildEmptyTranscriptDoc(youtubeVideoId, now),
        status: "pending",
    };
}
export function buildTranscriptAvailablePayload(target, transcript, now) {
    const fullText = buildTranscriptFullText(transcript.segments);
    const durationMs = getTranscriptDurationMs(transcript.segments);
    const storagePath = buildVideoTranscriptStoragePath(target.youtubeVideoId, VIDEO_TRANSCRIPT_VERSION);
    const storagePayload = {
        youtubeVideoId: target.youtubeVideoId,
        version: VIDEO_TRANSCRIPT_VERSION,
        source: "youtube",
        language: transcript.language,
        languageName: null,
        isAutoGenerated: null,
        fetchedAt: new Date().toISOString(),
        durationMs,
        fullText,
        segments: transcript.segments,
    };
    const docPayload = {
        ...buildEmptyTranscriptDoc(target.youtubeVideoId, now),
        ...buildAvailableRetryFields(),
        availableLanguages: transcript.availableLanguages,
        durationMs,
        fetchedAt: now,
        fullTextPreview: buildTranscriptPreview(fullText),
        language: transcript.language,
        lastCheckedAt: now,
        segmentCount: transcript.segments.length,
        status: "available",
        storagePath,
        textLength: fullText.length,
        updatedAt: now,
    };
    return {
        docPayload,
        storagePath,
        storagePayload,
    };
}
export function buildTranscriptFailedDoc(youtubeVideoId, status, errorCode, errorMessage, availableLanguages, retryCount, now, nextRetryAt) {
    const docPayload = {
        ...buildEmptyTranscriptDoc(youtubeVideoId, now),
        ...buildFailedRetryFields(retryCount, now, nextRetryAt, errorCode),
        availableLanguages,
        errorCode,
        errorMessage,
        lastCheckedAt: now,
        status,
        updatedAt: now,
    };
    return docPayload;
}
