import { VIDEO_TRANSCRIPT_VERSION, } from "./schema.js";
const RETRY_DELAYS_IN_DAYS = [7, 14, 30];
export function getTranscriptRetryDelayDays(retryCount) {
    const normalizedRetryCount = Math.max(1, retryCount);
    return RETRY_DELAYS_IN_DAYS[Math.min(normalizedRetryCount - 1, RETRY_DELAYS_IN_DAYS.length - 1)];
}
export function addDays(date, days) {
    return new Date(date.getTime() + days * 24 * 60 * 60 * 1000);
}
export function buildNextRetryDate(now, retryCount) {
    return addDays(now, getTranscriptRetryDelayDays(retryCount));
}
export function buildFailedRetryFields(retryCount, now, nextRetryAt, lastRetryReason) {
    return {
        retryCount,
        lastRetryAt: now,
        nextRetryAt,
        lastRetryReason,
    };
}
export function buildAvailableRetryFields() {
    return {
        retryCount: 0,
        lastRetryAt: null,
        nextRetryAt: null,
        lastRetryReason: null,
    };
}
export function getExistingRetryCount(doc) {
    return typeof doc?.retryCount === "number" && Number.isFinite(doc.retryCount)
        ? doc.retryCount
        : 0;
}
export function buildEmptyTranscriptDoc(youtubeVideoId, now) {
    return {
        youtubeVideoId,
        source: "youtube",
        status: "pending",
        language: null,
        languageName: null,
        isAutoGenerated: null,
        availableLanguages: [],
        storagePath: null,
        version: VIDEO_TRANSCRIPT_VERSION,
        segmentCount: 0,
        durationMs: null,
        textLength: 0,
        fullTextPreview: null,
        fetchedAt: null,
        updatedAt: now,
        lastCheckedAt: now,
        errorCode: null,
        errorMessage: null,
        retryCount: 0,
        lastRetryAt: null,
        nextRetryAt: null,
        lastRetryReason: null,
    };
}
