import { fireEvent, render, screen } from '@testing-library/react';
import { beforeAll, describe, expect, it, vi } from 'vitest';
import { VideoTranscriptPanel } from './VideoTranscriptPanel';
import type { VideoTranscriptStoragePayload } from '../../../types/videoTranscripts';

// jsdom не реализует Element.scrollTo — авто-скролл следования падал бы в эффекте
beforeAll(() => {
  Object.defineProperty(HTMLElement.prototype, 'scrollTo', {
    configurable: true,
    writable: true,
    value: vi.fn(),
  });
});

const TWO_PARAGRAPH_TRANSCRIPT: VideoTranscriptStoragePayload = {
  youtubeVideoId: 'video-1',
  version: 1,
  source: 'youtube',
  language: 'ru',
  languageName: 'Russian',
  isAutoGenerated: true,
  fetchedAt: '2026-03-09T10:00:00.000Z',
  durationMs: 120000,
  fullText: 'Первый фрагмент Второй фрагмент',
  segments: [
    { index: 0, startMs: 32000, endMs: 36000, durationMs: 4000, text: 'Первый фрагмент' },
    { index: 1, startMs: 47000, endMs: 52000, durationMs: 5000, text: 'Второй фрагмент' },
  ],
};

describe('VideoTranscriptPanel', () => {
  it('поиск фильтрует абзацы и подсвечивает совпадения', () => {
    render(
      <VideoTranscriptPanel
        courseId="development"
        error={null}
        isChecking={false}
        isLoading={false}
        onTimestampClick={vi.fn()}
        periodId="period-1"
        transcript={TWO_PARAGRAPH_TRANSCRIPT}
      />
    );

    fireEvent.change(screen.getByLabelText('Поиск по транскрипту'), {
      target: { value: 'второй' },
    });

    expect(screen.getByText('Найдено абзацев: 1')).toBeInTheDocument();
    expect(screen.queryByText('Первый фрагмент')).not.toBeInTheDocument();
    expect(screen.getByText('Второй').tagName).toBe('MARK');
  });

  it('живая позиция приоритетнее deep-link подсветки: рамка не залипает на ?t=', () => {
    render(
      <VideoTranscriptPanel
        courseId="development"
        error={null}
        focusTimeMs={48000}
        highlightedStartMs={33000}
        isChecking={false}
        isLoading={false}
        onTimestampClick={vi.fn()}
        periodId="period-1"
        transcript={TWO_PARAGRAPH_TRANSCRIPT}
      />
    );

    expect(
      screen.getByText('Второй фрагмент').closest('[data-start-ms="47000"]')
    ).toHaveClass('border-accent');
    expect(
      screen.getByText('Первый фрагмент').closest('[data-start-ms="32000"]')
    ).not.toHaveClass('border-accent');
  });

  it('без живой позиции deep-link подсветка работает как раньше', () => {
    render(
      <VideoTranscriptPanel
        courseId="development"
        error={null}
        focusTimeMs={null}
        highlightedStartMs={33000}
        isChecking={false}
        isLoading={false}
        onTimestampClick={vi.fn()}
        periodId="period-1"
        transcript={TWO_PARAGRAPH_TRANSCRIPT}
      />
    );

    expect(
      screen.getByText('Первый фрагмент').closest('[data-start-ms="32000"]')
    ).toHaveClass('border-accent');
  });

  it('ручной скролл выключает следование, кнопка возвращает к текущему месту', () => {
    const { container } = render(
      <VideoTranscriptPanel
        courseId="development"
        error={null}
        focusTimeMs={null}
        isChecking={false}
        isLoading={false}
        onTimestampClick={vi.fn()}
        periodId="period-1"
        transcript={TWO_PARAGRAPH_TRANSCRIPT}
      />
    );

    expect(
      screen.queryByRole('button', { name: '↓ К текущему месту' })
    ).not.toBeInTheDocument();

    const scrollContainer = container.querySelector('.overflow-y-auto') as HTMLDivElement;
    fireEvent.scroll(scrollContainer);

    const resumeButton = screen.getByRole('button', { name: '↓ К текущему месту' });
    fireEvent.click(resumeButton);

    expect(
      screen.queryByRole('button', { name: '↓ К текущему месту' })
    ).not.toBeInTheDocument();
  });

  it('перематывает видео по клику на таймкод транскрипта', () => {
    const handleTimestampClick = vi.fn();

    render(
      <VideoTranscriptPanel
        courseId="development"
        error={null}
        isChecking={false}
        isLoading={false}
        onTimestampClick={handleTimestampClick}
        periodId="period-1"
        transcript={{
          youtubeVideoId: 'video-1',
          version: 1,
          source: 'youtube',
          language: 'ru',
          languageName: 'Russian',
          isAutoGenerated: true,
          fetchedAt: '2026-03-09T10:00:00.000Z',
          durationMs: 120000,
          fullText: 'Первый фрагмент',
          segments: [
            {
              index: 0,
              startMs: 32000,
              endMs: 36000,
              durationMs: 4000,
              text: 'Первый фрагмент',
            },
          ],
        }}
      />
    );

    fireEvent.click(screen.getByRole('button', { name: 'Перейти к 00:32' }));

    expect(handleTimestampClick).toHaveBeenCalledWith(32000);
  });

  it('центрирует transcript по актуальному времени видео при открытии панели', () => {
    const scrollTo = vi.fn();
    const { container, rerender } = render(
      <VideoTranscriptPanel
        courseId="development"
        error={null}
        focusTimeMs={null}
        isChecking={false}
        isLoading={false}
        onTimestampClick={() => {}}
        periodId="period-1"
        transcript={{
          youtubeVideoId: 'video-1',
          version: 1,
          source: 'youtube',
          language: 'ru',
          languageName: 'Russian',
          isAutoGenerated: true,
          fetchedAt: '2026-03-09T10:00:00.000Z',
          durationMs: 120000,
          fullText: 'Первый фрагмент Второй фрагмент',
          segments: [
            {
              index: 0,
              startMs: 32000,
              endMs: 36000,
              durationMs: 4000,
              text: 'Первый фрагмент',
            },
            {
              index: 1,
              startMs: 47000,
              endMs: 52000,
              durationMs: 5000,
              text: 'Второй фрагмент',
            },
          ],
        }}
      />
    );

    const scrollContainer = container.querySelector('.overflow-y-auto') as HTMLDivElement;
    const focusedCard = container.querySelector('[data-start-ms="47000"]') as HTMLDivElement;

    Object.defineProperty(scrollContainer, 'clientHeight', {
      configurable: true,
      value: 400,
    });
    Object.defineProperty(focusedCard, 'offsetTop', {
      configurable: true,
      value: 260,
    });
    Object.defineProperty(focusedCard, 'offsetHeight', {
      configurable: true,
      value: 80,
    });
    scrollContainer.scrollTo = scrollTo;

    rerender(
      <VideoTranscriptPanel
        courseId="development"
        error={null}
        focusTimeMs={49000}
        isChecking={false}
        isLoading={false}
        onTimestampClick={() => {}}
        periodId="period-1"
        transcript={{
          youtubeVideoId: 'video-1',
          version: 1,
          source: 'youtube',
          language: 'ru',
          languageName: 'Russian',
          isAutoGenerated: true,
          fetchedAt: '2026-03-09T10:00:00.000Z',
          durationMs: 120000,
          fullText: 'Первый фрагмент Второй фрагмент',
          segments: [
            {
              index: 0,
              startMs: 32000,
              endMs: 36000,
              durationMs: 4000,
              text: 'Первый фрагмент',
            },
            {
              index: 1,
              startMs: 47000,
              endMs: 52000,
              durationMs: 5000,
              text: 'Второй фрагмент',
            },
          ],
        }}
      />
    );

    expect(scrollTo).toHaveBeenCalledWith({
      behavior: 'auto',
      top: 100,
    });
    expect(screen.getByText('Второй фрагмент').closest('[data-start-ms="47000"]')).toHaveClass(
      'border-accent'
    );
  });
});
