import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { VideoTranscriptPanel } from './VideoTranscriptPanel';

describe('VideoTranscriptPanel', () => {
  it('перематывает видео по клику на таймкод транскрипта', () => {
    const handleTimestampClick = vi.fn();

    render(
      <VideoTranscriptPanel
        error={null}
        isChecking={false}
        isLoading={false}
        onTimestampClick={handleTimestampClick}
        transcript={{
          youtubeVideoId: 'video-1',
          version: 1,
          source: 'youtube',
          language: 'ru',
          languageName: 'Russian',
          isAutoGenerated: true,
          fetchedAt: '2026-03-09T10:00:00.000Z',
          durationMs: 120000,
          fullText: 'Первый фрагмент',
          segments: [
            {
              index: 0,
              startMs: 32000,
              endMs: 36000,
              durationMs: 4000,
              text: 'Первый фрагмент',
            },
          ],
        }}
      />
    );

    fireEvent.click(screen.getByRole('button', { name: '00:32' }));

    expect(handleTimestampClick).toHaveBeenCalledWith(32000);
  });
});
