// This file is auto-generated by scripts/generate_event_icons.py
// Do not edit manually.

export const EVENT_ICONS = [
  {
    "id": "baby-swaddle",
    "name": "Младенец",
    "filename": "baby-swaddle.png"
  },
  {
    "id": "baby-feet",
    "name": "Следы малыша",
    "filename": "baby-feet.png"
  },
  {
    "id": "heart-message",
    "name": "Сообщение с сердцем",
    "filename": "heart-message.png"
  },
  {
    "id": "friendship",
    "name": "Друзья",
    "filename": "friendship.png"
  },
  {
    "id": "celebration-balloons",
    "name": "Праздничные шары",
    "filename": "celebration-balloons.png"
  },
  {
    "id": "pet-paw",
    "name": "Лапка питомца",
    "filename": "pet-paw.png"
  },
  {
    "id": "school-backpack",
    "name": "Школьный рюкзак",
    "filename": "school-backpack.png"
  },
  {
    "id": "report-card",
    "name": "Отличная оценка",
    "filename": "report-card.png"
  },
  {
    "id": "graduation-cap",
    "name": "Выпускная шапка",
    "filename": "graduation-cap.png"
  },
  {
    "id": "party-balloons",
    "name": "Праздник",
    "filename": "party-balloons.png"
  },
  {
    "id": "art-palette",
    "name": "Творчество",
    "filename": "art-palette.png"
  },
  {
    "id": "music-headphones",
    "name": "Музыка",
    "filename": "music-headphones.png"
  },
  {
    "id": "car",
    "name": "Автомобиль",
    "filename": "car.png"
  },
  {
    "id": "briefcase",
    "name": "Работа",
    "filename": "briefcase.png"
  },
  {
    "id": "cash",
    "name": "Финансы",
    "filename": "cash.png"
  },
  {
    "id": "key",
    "name": "Ключ",
    "filename": "key.png"
  },
  {
    "id": "house",
    "name": "Дом",
    "filename": "house.png"
  },
  {
    "id": "mortgage",
    "name": "Ипотека",
    "filename": "mortgage.png"
  },
  {
    "id": "passport",
    "name": "Паспорт",
    "filename": "passport.png"
  },
  {
    "id": "world-travel",
    "name": "Путешествие",
    "filename": "world-travel.png"
  },
  {
    "id": "id-card",
    "name": "Удостоверение",
    "filename": "id-card.png"
  },
  {
    "id": "graduation-diploma",
    "name": "Диплом",
    "filename": "graduation-diploma.png"
  },
  {
    "id": "love-letter",
    "name": "Письмо с сердцем",
    "filename": "love-letter.png"
  },
  {
    "id": "idea-book",
    "name": "Идея и книга",
    "filename": "idea-book.png"
  },
  {
    "id": "thermometer",
    "name": "Термометр",
    "filename": "thermometer.png"
  },
  {
    "id": "heart-nature",
    "name": "Забота о природе",
    "filename": "heart-nature.png"
  },
  {
    "id": "trophy",
    "name": "Кубок",
    "filename": "trophy.png"
  },
  {
    "id": "love-rings",
    "name": "Любовь",
    "filename": "love-rings.png"
  },
  {
    "id": "engagement-ring",
    "name": "Помолвка",
    "filename": "engagement-ring.png"
  },
  {
    "id": "baby-stroller",
    "name": "Коляска",
    "filename": "baby-stroller.png"
  },
  {
    "id": "visa-card",
    "name": "Виза",
    "filename": "visa-card.png"
  },
  {
    "id": "certificate",
    "name": "Сертификат",
    "filename": "certificate.png"
  },
  {
    "id": "handshake",
    "name": "Партнёрство",
    "filename": "handshake.png"
  },
  {
    "id": "heart-hands",
    "name": "Сердце в руках",
    "filename": "heart-hands.png"
  },
  {
    "id": "hammock",
    "name": "Отдых",
    "filename": "hammock.png"
  },
  {
    "id": "winner-cup",
    "name": "Победа",
    "filename": "winner-cup.png"
  },
  {
    "id": "baby-mobile",
    "name": "Детская погремушка",
    "filename": "baby-mobile.png"
  },
  {
    "id": "infinity-ring",
    "name": "Бесконечность",
    "filename": "infinity-ring.png"
  },
  {
    "id": "wedding-rings",
    "name": "Свадебные кольца",
    "filename": "wedding-rings.png"
  },
  {
    "id": "prayer-hands",
    "name": "Поддержка",
    "filename": "prayer-hands.png"
  },
  {
    "id": "custom-icon",
    "name": "Пользовательская иконка",
    "filename": "custom-icon.png"
  }
] as const;

export type EventIconId = typeof EVENT_ICONS[number]['id'];

export const EVENT_ICON_MAP: Record<EventIconId, (typeof EVENT_ICONS)[number]> = EVENT_ICONS.reduce(
  (acc, icon) => {
    acc[icon.id] = icon;
    return acc;
  },
  {} as Record<EventIconId, (typeof EVENT_ICONS)[number]>
);
